version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: rps_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - mariadb
  php-fpm:
    image: php:8.1.16-fpm
    container_name: rps_php-fpm
    volumes:
      - ./backend:/var/www/html
      - ./data/logs:/var/log/backend
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
    command:
      - /bin/sh
      - -c
      - |
        mkdir /var/log/backend
        docker-php-ext-install mysqli
        echo "mysqli installed...starting php-fpm..."
        php-fpm
    links:
      - mariadb
  composer:
    build: ./composer/
    container_name: rps_composer
    environment:
      - COMPOSER=/var/www/html/composer.json
    command:
      - /bin/sh
      - -c
      - |
        composer -vvv update
        composer -vvv install --working-dir=/var/www/html/
    volumes:
      - ./src:/var/www/html
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: rps_pma
    environment:
      - PHPMYADMIN_USER=root
      - PHPMYADMIN_PASSWORD=c3HbQQWffZpUfqxb
      - PHPMYADMIN_DATABASE=rock_paper_scissors
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    links:
      - mariadb
    ports: 
      - "8082:80"
  mariadb:
    container_name: rps_mariadb
    image: mariadb:latest
    ports:
      - "3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=c3HbQQWffZpUfqxb
      - MARIADB_DATABASE=rock_paper_scissors
  socket_server:
    build: ./socket_server/
    container_name: rps_socket_server
    ports: 
    - "3001:3001"
    environment:
      - SOCKET_SERVER_PORT=3001
      - SOCKET_SERVER_HOST=localhost
      - HTTP_PROTOCOL_TYPE=http
      - SECRET_KEY=t32ads90_78-fda8?f09dfa89dfadfle
      - CORS_ORIGIN=*
      - NGINX_IP=rps_nginx
      - VERBOSE_LOGS=true
    restart: unless-stopped
networks:
  default:
